const VERSION_MAJOR = 0;
const VERSION_MINOR = 0;
const VERSION_PATCH = 5;

const VERSION_STRING = `v${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}`;

export { VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, VERSION_STRING };
